version: '3.7'
services:
  app:
    build: .
    env_file:
      - .env
    command: yarn start
    volumes:
      - .:/app
      - yarn_cache:/yarn
      - node_modules_cache:/app/node_modules
    ports:
      - 8080:8080

volumes:
  yarn_cache:
  node_modules_cache:
